<?php

require getenv('SCRIPT_DIR') . 'Collections.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-04 at 10:39:06.
 */
class CollectionsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Collections
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Collections;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        unset($this->object);
    }

    /**
     * @dataProvider providertestCreateCollectionArray
     * @covers Collections::CreateCollectionArray
     * @todo   Implement testCreateCollectionArray().
     */
    public function testCreateCollectionArray($value, $expectedResult) {

        $result = $this->object->createCollectionArray($value);
        $this->assertEquals($result, $expectedResult);
    }

    public function providertestCreateCollectionArray() {
        return array(
            array('een collectie', array(), TRUE),
            array('', array('EEN COLLECTIE' => 'een collectie'), FALSE),
        );
    }

    /**
     * @dataProvider providertestInsertCollection
     * @covers Collections::insertCollection
     * @todo   Implement testInsertCollection().
     */
    //public function testInsertCollection($type, $idno, $status, $access, $locale, $name, $log, $expectedResult) {
    public function testInsertCollection() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    public function providertestInsertCollection() {
        return array(
            array(1, 1)
        );
    }

}
