<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-17 at 11:36:12.
 */
class EntitiesUitObjectenTest extends PHPUnit_Framework_TestCase {

    /**
     * @var EntitiesUitObjecten
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new EntitiesUitObjecten;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers EntitiesUitObjecten::createEntitiesArray
     * @todo   Implement testCreateEntitiesArray().
     */
    public function testCreateEntitiesArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
