<?php

require 'c:/xampp/htdocs/cag_tools/classes/Lists.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-17 at 11:36:25.
 */
class ListsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Lists
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Lists;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Lists::createGList
     * @todo   Implement testCreateList().
     */
    public function testCreateList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Lists::createListItem
     * @todo   Implement testCreateListItem().
     */
    public function testCreateListItem() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
