<?php

require 'c:/xampp/htdocs/cag_tools/classes/MyFunctions_new.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-14 at 15:48:04.
 */
class MyFunctions_newTest extends PHPUnit_Framework_TestCase {

    /**
     * @var MyFunctions_new
     */
    protected $func;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->func = new MyFunctions_new;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        unset($this->func);
    }

    /**
     * @covers MyFunctions_new::idLocale
     * @todo   Implement testIdLocale().
     */
    public function testIdLocale($taal) {
        $expectedResult = 1;
        $result = $this->func->idLocale($taal);
        $this->assertEquals($result, $expectedResult);
    }

    /**
     * @expectedException Exception
     * @expectedExceptionMessage Locale_id is leeg
     * @covers MyFunctions_new::idLocale
     * @todo   Implement testIdLocale().
     */
    public function testIdLocaleException() {
        $result = $this->object->idLocale('nl_NL');
        $this->assertEquals($result, '');
    }

    /**
     * @covers MyFunctions_new::setLogging
     * @todo   Implement testSetLogging().
     */
    public function testSetLogging() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyFunctions_new::ReadMappingcsv
     * @todo   Implement testReadMappingcsv().
     */
    public function testReadMappingcsv() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyFunctions_new::ReadXMLnode
     * @todo   Implement testReadXMLnode().
     */
    public function testReadXMLnode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyFunctions_new::XMLArraytoResultArray
     * @todo   Implement testXMLArraytoResultArray().
     */
    public function testXMLArraytoResultArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyFunctions_new::value_in_array
     * @todo   Implement testValue_in_array().
     */
    public function testValue_in_array() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyFunctions_new::createList
     * @todo   Implement testCreateList().
     */
    public function testCreateList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyFunctions_new::createListItem
     * @todo   Implement testCreateListItem().
     */
    public function testCreateListItem() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyFunctions_new::createPlace
     * @todo   Implement testCreatePlace().
     */
    public function testCreatePlace() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyFunctions_new::createEntity
     * @todo   Implement testCreateEntity().
     */
    public function testCreateEntity() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyFunctions_new::createListItem2
     * @todo   Implement testCreateListItem2().
     */
    public function testCreateListItem2() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyFunctions_new::TweeTotSingleField
     * @todo   Implement testTweeTotSingleField().
     */
    public function testTweeTotSingleField() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyFunctions_new::Herhalen
     * @todo   Implement testHerhalen().
     */
    public function testHerhalen() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyFunctions_new::makeArray
     * @todo   Implement testMakeArray().
     */
    public function testMakeArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyFunctions_new::makeArray2
     * @todo   Implement testMakeArray2().
     */
    public function testMakeArray2() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @dataProvider providertestCleanDate
     * @covers MyFunctions_new::cleanDate
     * @todo   Implement testCleanDate().
     */
    public function testCleanDate($variableOne, $type, $expectedResult) {
        // Remove the following lines when you implement this test.
        $t_func = new MyFunctions_new();
        $result = $t_func->cleanDate($variableOne, $type);
        $this->assertEquals($expectedResult, $result);
    }

    public function providertestCleanDate() {
        return array(
            array('kort na 1920 ', 'links', '1920'),
            array(' exact 1234', 'rechts', '1234'),
        );
    }

    /**
     * @covers MyFunctions_new::stringJoin
     * @todo   Implement testStringJoin().
     */
    public function testStringJoin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyFunctions_new::Initialiseer
     * @todo   Implement testInitialiseer().
     */
    public function testInitialiseer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyFunctions_new::Vernietig
     * @todo   Implement testVernietig().
     */
    public function testVernietig() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyFunctions_new::createContainer
     * @todo   Implement testCreateContainer().
     */
    public function testCreateContainer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyFunctions_new::createRelationship
     * @todo   Implement testCreateRelationship().
     */
    public function testCreateRelationship() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyFunctions_new::check_input
     * @todo   Implement testCheck_input().
     */
    public function testCheck_input() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MyFunctions_new::is_valid_date
     * @todo   Implement testIs_valid_date().
     */
    public function testIs_valid_date() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
