<?php

require 'c:/xampp/htdocs/cag_tools/classes/Objects.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-21 at 15:02:18.
 */
class ObjectsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Objects
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @dataProvider actionProvider
     * @covers Objects::actionToTake
     * @todo   Implement testActionToTake().
     */
    public function testActionToTakeReturnValue($input, $expectedOutput) {

        $object = new Objects();

        $this->assertInternalType("string", $input);
        $actualOutput = $object->actionToTake($input);
        $this->assertEquals($expectedOutput, $actualOutput);

    }

    public function actionProvider() {

        return array(
            array('', NULL),
            array('new_0001', NULL),
            array('00000001', 1)
         );
    }

    /**
     * @covers Objects::defineIdentificatie
     * @todo   Implement testDefineIdentificatie().
     */
    public function testDefineIdentificatie() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Objects::defineStatus
     * @todo   Implement testDefineStatus().
     */
    public function testDefineStatus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Objects::insertObject
     * @todo   Implement testInsertObject().
     */
    public function testInsertObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Objects::addSomeObjectAttribute
     * @todo   Implement testAddSomeObjectAttribute().
     */
    public function testAddSomeObjectAttribute() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Objects::createRelationship
     * @todo   Implement testCreateRelationship().
     */
    public function testCreateRelationship() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Objects::processVariable
     * @todo   Implement testProcessVariable().
     */
    public function testProcessVariable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
